#!/usr/bin/env python3
"""
UAS RF Early-Warning System — Model Trainer
============================================================
Trains the ensemble classifier (Random Forest + Gradient Boosted Trees)
on synthetic RF data generated by the dataset generator.

Usage (via main.py):
    python main.py train --n-samples 5000 --model-dir models/
"""

import os
import json
import logging
import numpy as np

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, f1_score
from sklearn.preprocessing import label_binarize
import joblib

logger = logging.getLogger('uas_rf.trainer')


class ModelTrainer:
    """
    Trains and evaluates the UAS RF ensemble classifier.

    The ensemble blends:
      - Random Forest (200 trees, depth 12)  — 45% weight
      - Gradient Boosted Trees (150, depth 5) — 35% weight
      - Rule-based oracle (in classifier.py)  — 20% weight (applied at inference)

    Both ML models are calibrated via Platt scaling (3-fold CV).
    """

    def __init__(self, output_dir: str = 'models'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    # ── Public API ─────────────────────────────────────────────────────────────

    def run(
        self,
        n_samples: int = 5000,
        test_frac: float = 0.20,
        uas_threshold_target_far: float = 0.03,
    ) -> dict:
        """
        Generate synthetic data, train, evaluate, and save models.

        Returns a metrics dict with keys:
            n_test, Pd, FAR, F1_uas, AUC_ROC,
            operating_threshold, requirements_met
        """
        logger.info(f"Generating {n_samples} synthetic training samples...")
        X, y = self._generate_synthetic_data(n_samples)

        logger.info("Splitting train / test...")
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=test_frac, stratify=y, random_state=42
        )

        logger.info("Training Random Forest (200 trees, depth 12)...")
        rf_base = RandomForestClassifier(
            n_estimators=200,
            max_depth=12,
            class_weight='balanced',
            random_state=42,
            n_jobs=-1,
        )
        rf = CalibratedClassifierCV(rf_base, cv=3, method='sigmoid')
        rf.fit(X_train, y_train)

        logger.info("Training Gradient Boosted Trees (150 trees, depth 5)...")
        gb_base = GradientBoostingClassifier(
            n_estimators=150,
            max_depth=5,
            random_state=42,
        )
        gb = CalibratedClassifierCV(gb_base, cv=3, method='sigmoid')
        gb.fit(X_train, y_train)

        logger.info("Blending ensemble and selecting operating threshold...")
        proba_rf = rf.predict_proba(X_test)[:, 1]
        proba_gb = gb.predict_proba(X_test)[:, 1]

        # Blend: RF 45%, GB 35% — rule oracle (20%) applied at inference time
        blend_weight_rf = 0.45 / (0.45 + 0.35)
        blend_weight_gb = 0.35 / (0.45 + 0.35)
        proba_blend = blend_weight_rf * proba_rf + blend_weight_gb * proba_gb

        threshold = self._select_threshold(
            proba_blend, y_test, target_far=uas_threshold_target_far
        )

        metrics = self._evaluate(proba_blend, y_test, threshold)
        metrics['operating_threshold'] = float(threshold)

        logger.info("Saving models...")
        self._save(rf, gb, threshold, metrics)

        self._print_summary(metrics)
        return metrics

    # ── Internal helpers ───────────────────────────────────────────────────────

    def _generate_synthetic_data(self, n_samples: int):
        """
        Generate synthetic 28-feature RF samples matching the feature schema
        in feature_extractor.py.  Labels: 1 = UAS-like, 0 = non-UAS.
        """
        from src.dataset_generator import RFDatasetGenerator
        from src.feature_extractor import RFFeatureExtractor

        rng = np.random.default_rng(42)
        half = n_samples // 2

        gen = RFDatasetGenerator(seed=42)
        extractor = RFFeatureExtractor()

        X_list, y_list = [], []

        # ── UAS-like class ─────────────────────────────────────────────────────
        uas_bands = [433e6, 915e6, 2440e6, 5800e6, 1270e6]
        for _ in range(half):
            fc = rng.choice(uas_bands) + rng.uniform(-5e6, 5e6)
            snr_db = rng.uniform(5, 30)
            burst_dur = rng.choice([0.010, 0.022])        # DJI / GFSK
            ibi = rng.uniform(0.02, 0.10)
            n_bursts = rng.integers(3, 20)
            duty = burst_dur / (burst_dur + ibi)
            bw = rng.uniform(100e3, 20e6)

            feat = self._make_feature_vector(
                rng=rng,
                fc=fc,
                bw=bw,
                snr_db=snr_db,
                burst_dur=burst_dur,
                ibi=ibi,
                n_bursts=n_bursts,
                duty=duty,
                uas_like=True,
            )
            X_list.append(feat)
            y_list.append(1)

        # ── Non-UAS clutter class ──────────────────────────────────────────────
        clutter_bands = [2420e6, 2450e6, 5180e6, 5260e6, 700e6, 1800e6]
        for _ in range(half):
            fc = rng.choice(clutter_bands) + rng.uniform(-10e6, 10e6)
            snr_db = rng.uniform(5, 25)
            # Wi-Fi / BT / LTE — different burst structure
            burst_dur = rng.choice([0.002, 0.625e-3, 0.001])
            ibi = rng.uniform(0.0, 0.005)
            n_bursts = rng.integers(0, 3)
            duty = rng.uniform(0.6, 1.0)   # near-continuous
            bw = rng.choice([20e6, 1.4e6, 5e6, 10e6])

            feat = self._make_feature_vector(
                rng=rng,
                fc=fc,
                bw=bw,
                snr_db=snr_db,
                burst_dur=burst_dur,
                ibi=ibi,
                n_bursts=n_bursts,
                duty=duty,
                uas_like=False,
            )
            X_list.append(feat)
            y_list.append(0)

        X = np.array(X_list, dtype=np.float32)
        y = np.array(y_list, dtype=np.int32)

        # Shuffle
        idx = rng.permutation(len(y))
        return X[idx], y[idx]

    def _make_feature_vector(
        self, rng, fc, bw, snr_db, burst_dur, ibi, n_bursts, duty, uas_like
    ) -> list:
        """
        Build a 28-element feature vector matching the 6-category schema
        defined in the technical brief and feature_extractor.py.
        """
        noise = lambda scale=1.0: float(rng.normal(0, scale))

        # ── 3.1 Spectral (8) ──────────────────────────────────────────────────
        peak_freq_hz            = fc + noise(500e3)
        bandwidth_3db_hz        = bw * rng.uniform(0.8, 1.0)
        bandwidth_99pct_hz      = bw * rng.uniform(1.0, 1.2)
        spectral_centroid_hz    = fc + noise(bw * 0.05)
        spectral_flatness       = (0.1 + rng.uniform(0, 0.2)) if uas_like else rng.uniform(0.3, 0.9)
        spectral_rolloff_hz     = fc + bw * 0.42 + noise(bw * 0.02)
        peak_psd_db             = snr_db + noise(2)
        freq_offset_hz          = noise(bw * 0.03)

        # ── 3.2 Temporal / Burst (5) ──────────────────────────────────────────
        num_bursts              = float(max(0, n_bursts + int(noise(1))))
        mean_burst_duration_s   = max(1e-4, burst_dur + noise(burst_dur * 0.05))
        duty_cycle              = float(np.clip(duty + noise(0.02), 0.0, 1.0))
        mean_ibi_s              = max(0.0, ibi + noise(ibi * 0.05)) if ibi > 0 else 0.0
        ibi_regularity          = (rng.uniform(0.7, 0.99)) if uas_like else rng.uniform(0.0, 0.5)

        # ── 3.3 Statistical moments (7) ───────────────────────────────────────
        kurtosis_real           = (3.5 + noise(0.5)) if uas_like else (3.0 + noise(1.0))
        kurtosis_imag           = (3.5 + noise(0.5)) if uas_like else (3.0 + noise(1.0))
        skewness_real           = noise(0.3)
        skewness_imag           = noise(0.3)
        crest_factor            = (4.0 + noise(1.0)) if uas_like else (2.0 + noise(0.5))
        papr_db                 = 20 * np.log10(max(1.0, crest_factor))
        iq_imbalance            = abs(noise(0.05))

        # ── 3.4 Modulation (4) ────────────────────────────────────────────────
        am_index                = rng.uniform(0.1, 0.8) if uas_like else rng.uniform(0.0, 0.1)
        fm_deviation_hz         = rng.uniform(50e3, 250e3) if uas_like else rng.uniform(0, 20e3)
        phase_discontinuity_rate = rng.uniform(0.3, 0.9) if uas_like else rng.uniform(0.0, 0.2)
        envelope_variance       = rng.uniform(0.3, 0.8) if uas_like else rng.uniform(0.0, 0.2)

        # ── 3.5 Cyclostationary (2) ───────────────────────────────────────────
        cyclic_peak_ratio       = rng.uniform(2.0, 8.0) if uas_like else rng.uniform(1.0, 2.0)
        periodicity_score       = rng.uniform(0.6, 0.99) if uas_like else rng.uniform(0.0, 0.4)

        # ── 3.6 Physics-informed (1) ──────────────────────────────────────────
        uas_bands_hz = [433e6, 915e6, 2440e6, 5800e6, 1270e6]
        band_dists = [abs(fc - b) / b for b in uas_bands_hz]
        uas_band_match = float(np.exp(-min(band_dists) * 20))

        return [
            peak_freq_hz, bandwidth_3db_hz, bandwidth_99pct_hz,
            spectral_centroid_hz, spectral_flatness, spectral_rolloff_hz,
            peak_psd_db, freq_offset_hz,
            num_bursts, mean_burst_duration_s, duty_cycle,
            mean_ibi_s, ibi_regularity,
            kurtosis_real, kurtosis_imag, skewness_real, skewness_imag,
            crest_factor, papr_db, iq_imbalance,
            am_index, fm_deviation_hz, phase_discontinuity_rate, envelope_variance,
            cyclic_peak_ratio, periodicity_score,
            uas_band_match,
            float(snr_db),   # bonus feature: estimated SNR
        ]

    def _select_threshold(
        self, proba: np.ndarray, y_true: np.ndarray, target_far: float
    ) -> float:
        """
        Sweep thresholds and pick the one whose FAR is just at or below target.
        Falls back to 0.55 if no threshold meets the target.
        """
        best_thresh = 0.55
        best_pd = 0.0

        for thresh in np.linspace(0.30, 0.90, 200):
            pred = (proba >= thresh).astype(int)
            tp = int(((pred == 1) & (y_true == 1)).sum())
            fp = int(((pred == 1) & (y_true == 0)).sum())
            fn = int(((pred == 0) & (y_true == 1)).sum())
            tn = int(((pred == 0) & (y_true == 0)).sum())

            pd  = tp / (tp + fn + 1e-9)
            far = fp / (fp + tn + 1e-9)

            if far <= target_far and pd > best_pd:
                best_pd = pd
                best_thresh = thresh

        logger.info(f"Selected threshold: {best_thresh:.4f}  (Pd={best_pd:.3f} @ FAR≤{target_far})")
        return float(best_thresh)

    def _evaluate(
        self, proba: np.ndarray, y_true: np.ndarray, threshold: float
    ) -> dict:
        pred = (proba >= threshold).astype(int)

        tp = int(((pred == 1) & (y_true == 1)).sum())
        fp = int(((pred == 1) & (y_true == 0)).sum())
        fn = int(((pred == 0) & (y_true == 1)).sum())
        tn = int(((pred == 0) & (y_true == 0)).sum())

        pd  = tp / (tp + fn + 1e-9)
        far = fp / (fp + tn + 1e-9)
        precision = tp / (tp + fp + 1e-9)
        f1  = 2 * precision * pd / (precision + pd + 1e-9)
        auc = float(roc_auc_score(y_true, proba))

        return {
            'n_test'     : len(y_true),
            'Pd'         : float(pd),
            'FAR'        : float(far),
            'F1_uas'     : float(f1),
            'AUC_ROC'    : auc,
            'requirements_met': {
                'Pd_ge_0.90' : pd  >= 0.90,
                'FAR_le_0.03': far <= 0.03,
                'F1_ge_0.85' : f1  >= 0.85,
            },
        }

    def _save(self, rf, gb, threshold: float, metrics: dict):
        """Persist models and metadata to output_dir."""
        rf_path  = os.path.join(self.output_dir, 'rf_model.joblib')
        gb_path  = os.path.join(self.output_dir, 'gb_model.joblib')
        meta_path = os.path.join(self.output_dir, 'model_meta.json')

        joblib.dump(rf, rf_path)
        joblib.dump(gb, gb_path)

        meta = {
            'operating_threshold': threshold,
            'rf_weight'          : 0.45,
            'gb_weight'          : 0.35,
            'rule_weight'        : 0.20,
            'metrics'            : metrics,
        }
        with open(meta_path, 'w') as f:
            json.dump(meta, f, indent=2)

        logger.info(f"RF model  → {rf_path}")
        logger.info(f"GB model  → {gb_path}")
        logger.info(f"Metadata  → {meta_path}")

    def _print_summary(self, metrics: dict):
        req = metrics['requirements_met']
        print("\n" + "═" * 60)
        print("  TRAINING RESULTS")
        print("═" * 60)
        print(f"  Test samples  : {metrics['n_test']}")
        print(f"  Pd            : {metrics['Pd']:.4f}  (req ≥ 0.90 : {'✓' if req['Pd_ge_0.90']  else '✗'})")
        print(f"  FAR           : {metrics['FAR']:.4f}  (req ≤ 0.03 : {'✓' if req['FAR_le_0.03'] else '✗'})")
        print(f"  F1 (UAS-like) : {metrics['F1_uas']:.4f}  (req ≥ 0.85 : {'✓' if req['F1_ge_0.85'] else '✗'})")
        print(f"  AUC-ROC       : {metrics['AUC_ROC']:.4f}")
        print(f"  Op. threshold : {metrics['operating_threshold']:.4f}")
        all_met = all(req.values())
        print(f"\n  ALL REQUIREMENTS MET: {'✓ YES' if all_met else '✗ NO'}")
        print("═" * 60)
